### ISSUE TITLE
[question] Compatibility with regtest

### ISSUE THREAD

**Issue by Tony-Stark** [ORP967/Bitcoin_Core_RPC_par_address#1]
Hi,
I wanted to toy around with this nice library to view UTXOs by addresses not listed on a wallet, 
and was wondering if it works with regtest OOTB or at all.

Thank you!

**Comment by ORP967** [comment]
Hey Mr. Tony-Stark,

Thanks for the question. My whole idea behind this program was the liberty to be able to search any wallets within my Bitcoin RPC. Honestly, the thought of using it with Regtest hadn’t crossed my mind. So I don’t know if it would work.

If you or anyone finds a way to do this please let me know and I’ll update it along with your information so you can get the proper credit.

**Comment by Tony-Stark** [comment]
I ended up using a built in bitcoin-cli function - scantxoutset, filterred the needed address, and it seemed to work, and show me a list of the unspent tokens.  It works on regtest and it didn't require external libraries, although integration with python would be nice.

For my purpose, that's probably enough for now. 

Thanks! :)

**Comment by Tony-Stark** [comment]
I ended up using a built in bitcoin-cli function - scantxoutset, filterred the needed address, and it seemed to work, and show me a list of the unspent tokens. It works on regtest and it didn't require external libraries, although integration with python would be nice.

For my purpose, that's probably enough for now.

Thanks! :)
